#!/bin/bash
# Author: Luka Ruzic

MAXTRIES=3

### setup atlases (1-indexed)
ATLAS_DECODER=(\
"" \
"Harvard-Oxford Cortical Structural Atlas" \
"Harvard-Oxford Subcortical Structural Atlas" \
"JHU ICBM-DTI-81 White-Matter Labels" \
"JHU White-Matter Tractography Atlas" \
"Juelich Histological Atlas" \
"MNI Structural Atlas" \
"Oxford Thalamic Connectivity Probability Atlas" \
)

usage () {
    echo "
Usage: $0 <x> <y> <z> [options]
Description:  takes MNI coordinates (mm) <x> <y> <z> and returns a name, hemisphere, and Brodmann Area (given by the Talairach Daemon)
              searches for the most probable Brodmann Area* label within a 9x9x9 cube of the MNI coordinates
              if no such label is found, mm2label exits with exit status 9
              (* only cortical gray matter, no subcortical or cerebellar Talairach labels are given)
Options:
  -icbm
     use the ICBM Lancaster coordinate conversion (default: Brett coordinates) (only applies to TD, not -a atlases)
  -a [thr%] <ATLAS CODE>
     report from an FSL probabilistic atlas instead of the Talairach Daemon
     threshold regions at thr% (DEFAULT: 0%)
     (only integer percenteges allowed)
     ex: mm2label 0 0 0 -a 75% 1
ATLAS CODES:"
    for (( i=1; i<${#ATLAS_DECODER[*]} ; i++ )); do
	echo "          $i: ${ATLAS_DECODER[i]}"
    done

    exit ${1:-1}
}

# hidden in the usage because users should get used to using vox2mm instead
# but retained so as to not break anything already using the option    
#  -vox
#     convert input coordinates from MNI vox (2mm resolution) to MNI mm


too_many_tries() {
    echo "$0 is bombing out with $MAXTRIES failed queries of the Talairach Daemon" >&2
    exit 8
}

tdquery() {
#    java org.talairach.PointToTD 3:9,$1,$2,$3 2>&1 | tr '\n' %
    /usr/bin/java -cp /usr/local/talairach/talairach.jar org.talairach.PointToTD 3:9, $1, $2, $3 host=${4}:1600 | tr '\n' %
    [ ${PIPESTATUS[0]} -ne 0 ] && echo "ERROR: TD call failed"
}


### PARSE ARGUMENTS
PCT=0
n=0
while [ "$1" ]; do
    if [[ "$1" =~ -help ]]; then
	usage 0
    elif [[ "$1" =~ ^-{0,1}[0-9]*$ ]]; then
	COORDINATES+="$1 "
	let n++
	shift
    elif [ "$1" == "-icbm" ]; then
	ICBM=set
	shift
    elif [ "$1" == "-vox" ]; then
	VOX=set
	shift
    elif [ "$1" == "-a" ]; then
	if [ ${2:${#2}-1:1} == "%" ]; then PCT=${2%\%}; shift; fi
	ATLAS=("${ATLAS_DECODER[$2]}")
	if [ ! "$ATLAS" ]; then echo "ERROR: $2 is not a valid atlas code" >&2; exit 1; fi
	shift 2
    else 
	echo "UNRECOGNIZED ARGUMENT: $1" >&2
    fi
done

### error checking
if [ $n -ne 3 ]; then
    let e++; echo "ERROR: 3 and only 3 coordinates allowable" >&2
fi
if [[ "$p" =~ [^0-9] ]]; then
    let e++; echo "ERROR: only integers acceptable" >&2
fi

[ $e ] && usage

# retrieve label
if [ ! "$ATLAS" ]; then
    # convert to talairach coordinates
    [ $ICBM ] && t=($(icbm_mni2tal ${COORDINATES})) || t=($(mni2tal ${COORDINATES}))


    # submit to talairach daemon
    tdoutput="$(tdquery ${t[*]} localhost)"; let tries++
    # resubmit until there's no error
    until [ $(echo $tdoutput | grep -icE "error: td call failed|exception") -eq 0 ]; do
	[ $tries -ge $MAXTRIES ] && break
	echo "retrying Talairach Daemon" >&2
	tdoutput="$(tdquery ${t[*]} localhost)"; let tries++
	sleep 1
    done
    # try head node TD as a last ditch
    tdoutput="$tdquery ${t[*]} dream)"
    [ $(echo $tdoutput | grep -icE "error: td call failed|exception") -ne 0 ] && too_many_tries


    # parse into desired fields
    fields="$(echo $tdoutput | awk -F',' 'BEGIN {RS="%"} /Brodmann/ {print $1";" $3";" $5; exit}' | sed 's|*|_|g')"

    hemisphere="$(echo $fields | cut -d\; -f1 | grep -o '[LR]')"
    region="$(echo $fields | cut -d\; -f2 | tr ' ' _)"
    BArea="$(echo $fields | cut -d\; -f3 | cut -d" " -f3)"    

#    if [[ "$tdoutput" =~ Brodmann\ area ]];then # there's a BA
#	fields="$(echo $tdoutput | awk -F',' 'BEGIN {RS="%"} /Brodmann/ {print $1";" $3";" $5; exit}')"
#
#	hemisphere="$(echo $fields | cut -d\; -f1 | grep -Eo '^[LR]')"
#	region="$(echo $fields | cut -d\; -f2 | tr ' ' _)"
#	BArea="$(echo $fields | cut -d\; -f3 | cut -d" " -f3)"    
#    elif [[ "$tdoutput" =~ Cerebellum ]]; then # it's cerebellum
#	fields="$(echo $tdoutput | awk -F',' 'BEGIN {RS="%"} /Brodmann/ {print $1";" $3";" $5; exit}')"
#
#	hemisphere="$(echo $tdoutput | cut -d\; -f1 | grep -Eo '^[LR]')"
#	region="$()"
#	BArea="N/A"
#    elif [ ??? ]; then  # it's subcortical
#    else  # it's white matter	
#    fi



    # return output
    [ $region ] && echo "$region $([ $hemisphere ] && echo $hemisphere) $([ $BArea ] && echo BA$BArea)" || exit 9
else
    while read pct region; do 
	if [[ "$pct" =~ [^0-9] ]]; then
	    label+=" $pct $region;"
	else
	    [ $pct -ge $PCT ] && label+=" ${pct}% ${region};"
	fi
    done < <(atlasquery -a "$ATLAS" -c ${COORDINATES// /,} | sed -e 's|.*<br>||' -e 's|, \([0-9]*%\)|\n\1|g' -e 's|,|:|g' -e 's|%||g')
    echo $label | sed -e 's|^ ||' -e 's|;$||'
fi


exit 0
