#!/bin/bash
# AUTHOR: Luka Ruzic

usage() {
    echo "Usage: vox2mm <x> <y> <z>"

    exit ${1:-1}
}

[[ "$*" =~ -help ]] && usage 0
[ $# -ne 3 ] && usage
if [[ "$*" =~ [^0-9.\ ] ]] && [[ "$*" =~ - ]]; then 
    echo "no negative numbers"
    usage
fi


MNI_BRAIN=$(findMNI)

echo $1 $2 $3 | img2stdcoord -std $MNI_BRAIN -img $MNI_BRAIN | awk '{print $1,$2,$3}'


exit 0
